config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "ask", to: "questions#ask"
  get "answer", to: "questions#answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]
    if params[:question] === "I am going to work"
      @response = "Great!"
    elsif params[:question].match(/\?$/)
      @response = "Silly question, get dressed and go to work!"
    else
      @response = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="answer">
<h1>Stupid Coaching</h1>
<div class="card">
<p><%= @question %></p>

<p>-You</p>
</div>
<div class="card card-coach">
<p><%= @response %></p>

<p>-Your Coach</p>
</div>
<%= link_to "Return to Ask", ask_path %>
</div>

app/views/questions/ask.html.erb
<form action="/answer">
<h1>Stupid Coaching</h1>
<h3>Ask your coach anything:</h3>
<div>
  <input id="input-text" type="text" name="question" value="<%= params[:question] %>">
  <input id="submit-btn" type="submit" value="Ask!">
  </div>
</form>